# Generated by Django 4.2 on 2025-10-21 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="posts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi", "mkv", "webm"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(
                max_length=1000,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="Comment content cannot be empty."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="Post content cannot be empty."
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="content",
            field=models.TextField(
                blank=True,
                max_length=2000,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="Story content cannot be empty when provided."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="stories/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="stories/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi", "mkv"]
                    )
                ],
            ),
        ),
    ]
