# Generated by Django 4.2 on 2025-10-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_video_alter_comment_content_alter_post_content_and_more"),
    ]

    operations = []
