# Generated by Django 4.2 on 2025-10-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_created_at_profile_followers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
