# Generated by Django 4.2 on 2025-10-21 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(
                max_length=5000,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="Message content cannot be empty."
                    )
                ],
            ),
        ),
    ]
